<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Tag helpers to help integrate elmah.io client-side logging into ASP.NET Core.</Description>
    <Authors>elmah.io</Authors>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Elmah.Io.AspNetCore.TagHelpers</AssemblyName>
    <PackageId>Elmah.Io.AspNetCore.TagHelpers</PackageId>
    <PackageTags>Error;Exception;Reporting;Management;Logging;ELMAH;Diagnostics;Tracing;AspNetCore</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://elmah.io</PackageProjectUrl>
    <RepositoryUrl>https://github.com/elmahio/Elmah.Io.AspNetCore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <EnablePackageValidation>true</EnablePackageValidation>
    <LangVersion>12.0</LangVersion>
    <!-- SourceLink -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elmah.Io.AspNetCore\Elmah.Io.AspNetCore.csproj" />
  </ItemGroup>

</Project>
